version: '3'
services:
  dotfiles:
    image: hwata001/dotfiles:latest
      #platform: linux/amd64
      #profiles:
      #-extra
    volumes:
      - type: bind
        source: "../../"
        target: "/home"
      - type: bind
        source: "~/.ssh"
        target: "/root/.ssh"
      - type: bind
        source: "./my-gitconfig" #be copied from ~/.gitconfig
        target: "/root/.gitconfig""

