version: '3'
services:
  dotfiles:
    image: hwata001/dotfiles:latest
      #platform: linux/amd64
      #profiles:
      #-extra
    volumes:
      - type: bind
        source: "<you-working-dir>"
        target: "/home"
      - type: bind
        source: "<your-ssh-key>"
        target: "/root/.ssh"
    environment:
      - GIT_EMAIL=<you-git-email>
      - GIT_NAME=<you-git-name>

